library(stringr)
library(purrr)
library(tibble)
library(dplyr)
library(readr)
library(msgr)

options(msgr.level = 10)
devtools::load_all()


devtools::check(args = "--no-tests")
devtools::test()
devtools::test_coverage(type = "tests", quiet = FALSE)
devtools::spell_check()


devtools::test_file("tests/testthat/test-github-api.R")
devtools::test_file("tests/testthat/test-utilities.R")
devtools::test_file("tests/testthat/test-projects.R")
devtools::test_file("tests/testthat/test-columns.R")
devtools::test_file("tests/testthat/test-cards.R")
devtools::test_file("tests/testthat/test-users.R")
devtools::test_file("tests/testthat/test-organizations.R")
devtools::test_file("tests/testthat/test-teams.R")
devtools::test_file("tests/testthat/test-memberships.R")
devtools::test_file("tests/testthat/test-collaborators.R")
devtools::test_file("tests/testthat/test-repositories.R")
devtools::test_file("tests/testthat/test-labels.R")
devtools::test_file("tests/testthat/test-milestones.R")
devtools::test_file("tests/testthat/test-issues.R")
devtools::test_file("tests/testthat/test-pull-requests.R")


devtools::test_coverage_file("tests/testthat/test-github-api.R")
devtools::test_coverage_file("tests/testthat/test-utilities.R")
devtools::test_coverage_file("tests/testthat/test-projects.R")
devtools::test_coverage_file("tests/testthat/test-columns.R")
devtools::test_coverage_file("tests/testthat/test-cards.R")
devtools::test_coverage_file("tests/testthat/test-users.R")
devtools::test_coverage_file("tests/testthat/test-organizations.R")
devtools::test_coverage_file("tests/testthat/test-teams.R")
devtools::test_coverage_file("tests/testthat/test-memberships.R")
devtools::test_coverage_file("tests/testthat/test-collaborators.R")
devtools::test_coverage_file("tests/testthat/test-repositories.R")
devtools::test_coverage_file("tests/testthat/test-labels.R")
devtools::test_coverage_file("tests/testthat/test-milestones.R")
devtools::test_coverage_file("tests/testthat/test-issues.R")
devtools::test_coverage_file("tests/testthat/test-pull-requests.R")
